/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.KeyEvent;

/**
 *
 * @author laboratorio
 */
public class Menu extends javax.swing.JFrame {

    private StringBuffer historico = new StringBuffer();
    
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFrase = new javax.swing.JLabel();
        lblPesquisa = new javax.swing.JLabel();
        lblCaracteres = new javax.swing.JLabel();
        txtFrase = new javax.swing.JTextField();
        txtPesquisa = new javax.swing.JTextField();
        txtCaracteres = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaFrases = new javax.swing.JTextArea();
        lblTotalCaracteres = new javax.swing.JLabel();
        lblTotalPalavras = new javax.swing.JLabel();
        txtTotalPalavras = new javax.swing.JTextField();
        txtTotalCaracteres = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFrase.setText("Frase");

        lblPesquisa.setText("Pesquisa");

        lblCaracteres.setText("Caracteres");

        txtFrase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFraseKeyReleased(evt);
            }
        });

        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });

        txtCaracteres.setEditable(false);

        txaFrases.setEditable(false);
        txaFrases.setColumns(20);
        txaFrases.setRows(5);
        jScrollPane1.setViewportView(txaFrases);

        lblTotalCaracteres.setText("Total Caracteres");

        lblTotalPalavras.setText("Total Palavras");

        txtTotalPalavras.setEditable(false);

        txtTotalCaracteres.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCaracteres)
                            .addComponent(lblPesquisa, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFrase, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFrase, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPesquisa)
                            .addComponent(txtCaracteres)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalCaracteres)
                            .addComponent(lblTotalPalavras))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTotalCaracteres, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalPalavras, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFrase)
                    .addComponent(txtFrase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesquisa)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCaracteres)
                    .addComponent(txtCaracteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalCaracteres)
                    .addComponent(txtTotalCaracteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalPalavras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalPalavras))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contarCaracteres() {
        StringBuffer texto = new StringBuffer(txaFrases.getText());
        int totalCaracteres = texto.length();
        txtTotalCaracteres.setText(String.valueOf(totalCaracteres));
    }
    
    private void contarPalavras() {
        StringBuffer texto = new StringBuffer(txaFrases.getText().trim());
        String[] palavras = texto.toString().split("\\s+");
        int totalPalavras = palavras.length;
        txtTotalPalavras.setText(String.valueOf(totalPalavras));
    }
    
    private void txtFraseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFraseKeyReleased

        StringBuffer frase = new StringBuffer(txtFrase.getText());
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            historico.append(frase.toString().toUpperCase()).append("\n");
            txaFrases.setText(historico.toString());
            txtFrase.setText("");
        } else {
            txaFrases.setText(historico.toString() + frase.toString().toUpperCase());
        }
        
        contarCaracteres();
        contarPalavras();
    }//GEN-LAST:event_txtFraseKeyReleased

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        
        StringBuffer pesquisa = new StringBuffer(txtPesquisa.getText());
        
        if (historico.toString().toLowerCase().contains(pesquisa.toString())) {
            txtCaracteres.setText(pesquisa.toString().toUpperCase());
        }
    }//GEN-LAST:event_txtPesquisaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCaracteres;
    private javax.swing.JLabel lblFrase;
    private javax.swing.JLabel lblPesquisa;
    private javax.swing.JLabel lblTotalCaracteres;
    private javax.swing.JLabel lblTotalPalavras;
    private javax.swing.JTextArea txaFrases;
    private javax.swing.JTextField txtCaracteres;
    private javax.swing.JTextField txtFrase;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtTotalCaracteres;
    private javax.swing.JTextField txtTotalPalavras;
    // End of variables declaration//GEN-END:variables
}
